// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5CmXFJqjrF2y_Bxp32sM4K4rLBt3vA2Y',
    appId: '1:26985113436:web:df5f17cc38a57f93348399',
    messagingSenderId: '26985113436',
    projectId: 'whale-lumitech1',
    authDomain: 'whale-lumitech1.firebaseapp.com',
    storageBucket: 'whale-lumitech1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO61v4Hgr1M06mAJocVNalq5y-NXnbdDM',
    appId: '1:26985113436:android:96e9d051de1726cd348399',
    messagingSenderId: '26985113436',
    projectId: 'whale-lumitech1',
    storageBucket: 'whale-lumitech1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAheEzfkNZTwd2rQJuFrXqiT3pyINeLr-w',
    appId: '1:26985113436:ios:74a7e2bc9aa9d06e348399',
    messagingSenderId: '26985113436',
    projectId: 'whale-lumitech1',
    storageBucket: 'whale-lumitech1.appspot.com',
    iosBundleId: 'com.example.newsAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAheEzfkNZTwd2rQJuFrXqiT3pyINeLr-w',
    appId: '1:26985113436:ios:74a7e2bc9aa9d06e348399',
    messagingSenderId: '26985113436',
    projectId: 'whale-lumitech1',
    storageBucket: 'whale-lumitech1.appspot.com',
    iosBundleId: 'com.example.newsAppUi',
  );
}
